KdG-BCIT-ISSP/nest-core

.gitignore
Dockerfile
docker-compose.yml
src/main/java/com/nest/core/analytics_service/README.md
src/main/java/com/nest/core/comment_management_service/model/Comment.java
src/main/java/com/nest/core/config/SecurityConfig.java
src/main/java/com/nest/core/exception/GlobalExceptionHandler.java
src/main/java/com/nest/core/member_management_service/model/Member.java
src/main/java/com/nest/core/moderation_service/README.md
src/main/java/com/nest/core/notification_service/README.md
src/main/java/com/nest/core/post_management_service/model/Post.java
src/main/java/com/nest/core/report_management_service/model/Report.java
src/main/java/com/nest/core/search_service/README.md
src/main/java/com/nest/core/tag_management_service/model/Tag.java
src/main/java/com/nest/core/topic_management_service/model/Topic.java
src/main/resources/application.properties

- This commit contains 
-- 1. Project Hierarchy set
-- 2. Each model Entities are set based on the db tables

[NEST-BE-2] Create Entities

---

build.gradle
src/main/java/com/nest/core/CoreApplication.java
src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/config/SwaggerConfig.java

[NEST-BE-5] Setup Swagger UI

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java

[NEST-BE-4] Setup Docker Github Action

---

docker-compose.yml

[NEST-BE-4] Edit docker-compose.yml to align with github action

---

src/main/java/com/nest/core/member_management_service/dto/JoinMemberRequest.java
src/main/java/com/nest/core/member_management_service/model/Member.java
src/main/java/com/nest/core/member_management_service/service/MemberService.java

Add a line to set the avatar to a default profile picture url found on google images
- url likely needs to be changed later on if we will be using some other storage service to store images
- location of url variable should also be changed to somewhere more appropriate, for now I just left it in the MemberService class as a private static variable

[NEST-BE-9] Add logic to set default picture on sign-up

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/post_management_service/controller/ArticleApiController.java
src/main/java/com/nest/core/post_management_service/dto/CreateArticleRequest.java
src/main/java/com/nest/core/post_management_service/model/Post.java
src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/tag_management_service/model/Tag.java
src/main/java/com/nest/core/tag_management_service/repository/TagRepository.java
src/main/java/com/nest/core/topic_management_service/repository/TopicRepository.java

https://trello.com/c/N2YYwrHP/111-nest-be-14-create-api-endpoint-that-admin-able-to-create-the-article

[NEST-BE-14] Create Admin able to create article api

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/exception/GlobalExceptionHandler.java
src/main/java/com/nest/core/post_management_service/controller/ArticleApiController.java
src/main/java/com/nest/core/post_management_service/dto/GetArticleResponse.java
src/main/java/com/nest/core/post_management_service/exception/GetArticleFailException.java
src/main/java/com/nest/core/post_management_service/model/Post.java
src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/tag_management_service/model/Tag.java
src/main/java/com/nest/core/topic_management_service/model/Topic.java

https://trello.com/c/GYCeIY0H/112-nest-be-15-create-api-endpoint-that-user-able-to-read-the-article

[NEST-BE-15] Create User able to read article api

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/post_management_service/controller/ArticleApiController.java
src/main/java/com/nest/core/post_management_service/dto/CreateArticleRequest.java
src/main/java/com/nest/core/post_management_service/dto/EditArticleRequest.java
src/main/java/com/nest/core/post_management_service/dto/EditArticleResponse.java
src/main/java/com/nest/core/post_management_service/exception/EditArticleFailException.java
src/main/java/com/nest/core/post_management_service/model/Post.java
src/main/java/com/nest/core/post_management_service/model/PostTag.java
src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/repository/PostTagRepository.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/tag_management_service/model/Tag.java

https://trello.com/c/xvXRe4mg/113-nest-be-16-create-api-endpoint-that-admin-able-to-update-the-article

[NEST-BE-16] Edit ManyToMany to ManyToOne & create admin able to update article api

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/post_management_service/controller/ArticleApiController.java
src/main/java/com/nest/core/post_management_service/exception/DeleteArticleFailException.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java

https://trello.com/c/G0sQWP95/114-nest-be-17-create-api-endpoint-that-admin-able-to-delete-the-article

[NEST-BE-17] create admin able to delete article api

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/post_management_service/controller/ArticleApiController.java
src/main/java/com/nest/core/post_management_service/controller/PostApiController.java
src/main/java/com/nest/core/post_management_service/dto/CreatePostRequest.java
src/main/java/com/nest/core/post_management_service/dto/GetPostResponse.java
src/main/java/com/nest/core/post_management_service/dto/ImageHandler.java
src/main/java/com/nest/core/post_management_service/exception/GetPostFailException.java
src/main/java/com/nest/core/post_management_service/model/Post.java
src/main/java/com/nest/core/post_management_service/model/PostImage.java
src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/post_management_service/service/PostService.java

https://trello.com/c/i7rYP34O/108-nest-be-11-create-api-endpoint-that-able-to-read-user-posts-with-pageable-function

[NEST-BE-11] create user able to read user-post api

---

src/main/java/com/nest/core/post_management_service/controller/PostApiController.java
src/main/java/com/nest/core/post_management_service/dto/EditPostRequest.java
src/main/java/com/nest/core/post_management_service/dto/EditPostResponse.java
src/main/java/com/nest/core/post_management_service/exception/EditPostFailException.java
src/main/java/com/nest/core/post_management_service/service/PostService.java

https://trello.com/c/G3ZUvqSK/109-nest-be-12-create-api-endpoint-that-able-to-update-the-user-posts-title-content-tags

[NEST-BE-12] Create user able to edit user post api

---

src/main/java/com/nest/core/post_management_service/controller/PostApiController.java
src/main/java/com/nest/core/post_management_service/exception/DeletePostFailException.java
src/main/java/com/nest/core/post_management_service/service/PostService.java

https://trello.com/c/AnqHB4o8/110-nest-be-13-create-api-endpoint-that-able-to-delete-the-user-posts-by-user-who-created-and-admin-role

[NEST-BE-13] Create user able to delete user post api

---

src/main/java/com/nest/core/post_management_service/dto/CreateArticleRequest.java
src/main/java/com/nest/core/post_management_service/dto/EditArticleRequest.java
src/main/java/com/nest/core/post_management_service/dto/EditArticleResponse.java
src/main/java/com/nest/core/post_management_service/dto/GetArticleResponse.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java

https://trello.com/c/uRzWmzXJ/130-nest-be-22-update-create-read-put-api-to-handle-cover-image-for-article

[NEST-BE-22] Update CRU api to handle cover image for article

---

src/main/java/com/nest/core/CoreApplication.java
src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/post_management_service/controller/ContentInteractionController.java
src/main/java/com/nest/core/post_management_service/model/Post.java
src/main/java/com/nest/core/post_management_service/model/PostLike.java
src/main/java/com/nest/core/post_management_service/repository/PostLikeRepository.java
src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/service/ContentInteractionService.java

https://trello.com/c/0DAN5n3L/180-nest-be-27-create-api-endpoint-for-adding-likes-undo-for-userpost-and-article

[NEST-BE-27] Create API Endpoint for adding likes/undo for userpost, article

---

src/main/java/com/nest/core/comment_management_service/controller/CommentInteractionApiController.java
src/main/java/com/nest/core/comment_management_service/model/Comment.java
src/main/java/com/nest/core/comment_management_service/model/CommentLike.java
src/main/java/com/nest/core/comment_management_service/model/CommentLikeId.java
src/main/java/com/nest/core/comment_management_service/repository/CommentLikeRepository.java
src/main/java/com/nest/core/comment_management_service/repository/CommentRepository.java
src/main/java/com/nest/core/comment_management_service/service/CommentInteractionService.java

https://trello.com/c/acaBhX1z/181-nest-be-28-create-api-endpoint-for-adding-likes-undo-for-comments-on-userpost-and-article

[NEST-BE-28] comment likes toggle endpoint

---

src/main/java/com/nest/core/report_management_service/service/ReportService.java

[NEST-BE-33] Fix dumb bug

---

src/main/java/com/nest/core/comment_management_service/model/Comment.java

https://trello.com/c/naTRIskB/191-nest-be-34-refactoring-sprint3-tasks

[NEST-BE-34] refactor comment model

---

src/main/java/com/nest/core/post_management_service/controller/ContentInteractionController.java
src/main/java/com/nest/core/post_management_service/model/Bookmark.java
src/main/java/com/nest/core/post_management_service/model/BookmarkId.java
src/main/java/com/nest/core/post_management_service/repository/BookmarkRepository.java
src/main/java/com/nest/core/post_management_service/service/ContentInteractionService.java

[NEST-BE-34] refactor - get bookmark by type

[NEST-BE-34] refactor - get bookmark by type

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/notification_service/README.md
src/main/java/com/nest/core/notification_service/controller/NotificationApiController.java
src/main/java/com/nest/core/notification_service/dto/NotificationRequest.java
src/main/java/com/nest/core/notification_service/model/Notification.java
src/main/java/com/nest/core/notification_service/repository/NotificationRepository.java
src/main/java/com/nest/core/notification_service/service/NotificationService.java

[NEST-BE-37-38] api endpoint for notification

[NEST-BE-37-38] api endpoint for notification

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/member_management_service/controller/MemberApiController.java
src/main/java/com/nest/core/member_management_service/dto/GetAllUserProfileResponse.java
src/main/java/com/nest/core/member_management_service/service/MemberService.java

[NEST-BE-GetALLUsers] api endpoint for get all users

[NEST-BE-GetALLUsers] api endpoint for get all users

---

src/main/java/com/nest/core/post_management_service/model/Post.java

[NEST-BE-SET-CREATEAT-POST] Add created At

[NEST-BE-SET-CREATEAT-POST] Add created At

---

src/main/java/com/nest/core/search_service/dto/SearchResponse.java

- Add createdAt in search response

[NEST-BE-40-41-43] Sort by createdAt

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java

- Change security config file to allow unauthenticated users to get topics/tags

[NEST-BE-44-45] Allow unauthenticated user to get topics and tags

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/member_management_service/controller/MemberApiController.java
src/main/java/com/nest/core/member_management_service/dto/UpdateRoleRequest.java
src/main/java/com/nest/core/member_management_service/service/MemberService.java

[NEST-BE-39] Super Admin change the role

[NEST-BE-39] Super Admin change the role

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/config/RedisConfig.java
src/main/java/com/nest/core/post_management_service/controller/ContentInteractionController.java
src/main/java/com/nest/core/post_management_service/dto/ContentResponse.java
src/main/java/com/nest/core/post_management_service/dto/GetArticleResponse.java
src/main/java/com/nest/core/post_management_service/dto/GetPostResponse.java
src/main/java/com/nest/core/post_management_service/repository/PostLikeRepository.java
src/main/java/com/nest/core/post_management_service/service/ContentInteractionService.java

[NEST-BE-39] GET POST ARTICLE SPECIFIC ID + FIXES

[NEST-BE-39] GET POST ARTICLE SPECIFIC ID + FIXES

---

src/main/java/com/nest/core/comment_management_service/service/CommentInteractionService.java
src/main/java/com/nest/core/post_management_service/dto/GetArticleResponse.java
src/main/java/com/nest/core/post_management_service/dto/GetPostResponse.java
src/main/java/com/nest/core/search_service/service/SearchService.java

Refactor and add logs in Comment Interaction Service

[NEST-BE-39] Refactor Comment Interaction Service

---

src/main/java/com/nest/core/member_management_service/service/MemberService.java

Fix-role-update

---

src/main/java/com/nest/core/member_management_service/dto/GetAllUserProfileResponse.java

- Add region to get all members DTO

[NEST-BE-Patch] Add region to get all member response

---

src/main/java/com/nest/core/notification_service/service/NotificationService.java

[NEST-BE-Fix] Trigger docker compose build

[NEST-BE-Fix] Trigger docker compose build

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/post_management_service/controller/ArticleApiController.java
src/main/java/com/nest/core/post_management_service/controller/ContentInteractionController.java
src/main/java/com/nest/core/post_management_service/controller/PostApiController.java
src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/post_management_service/service/PostService.java

Create-API-send-posts-by-userId

[NEST-BE-52] Create-API-send-posts-by-userId

---

src/main/java/com/nest/core/search_service/controller/SearchApiController.java
src/main/java/com/nest/core/search_service/service/SearchService.java

API pagination for posts, articles

[NEST-BE-53] API pagination for posts, articles

---

src/main/java/com/nest/core/comment_management_service/dto/CreateCommentRequest.java
src/main/java/com/nest/core/comment_management_service/dto/GetCommentResponse.java
src/main/java/com/nest/core/comment_management_service/model/Comment.java
src/main/java/com/nest/core/comment_management_service/service/CommentService.java

Create user replies to comments
If parentID null -> it means the comment is an initial comment (or top-level comment)
If parentID exist -> parentID is the initial comment
the depth is only 2 -> comment can have reply-comments. But reply-comment can't have reply-comment.

[NEST-BE-54] Create user replies to comments

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/comment_management_service/controller/CommentApiController.java
src/main/java/com/nest/core/comment_management_service/dto/GetCommentResponse.java
src/main/java/com/nest/core/comment_management_service/repository/CommentRepository.java
src/main/java/com/nest/core/comment_management_service/service/CommentService.java
src/main/java/com/nest/core/member_management_service/dto/GetProfileResponse.java

gcho13@my.bcit.ca — 2:21 AM
- Comments should also include user name and avatar
- Member/me should also include user_id also in response (so that delete comments should be based on own user by comparing user id)
- Get comments by userId

Nest be 54 create api for user replies to comments

---

docker-compose.yml
src/main/resources/application.properties

auth update

---

src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/post_management_service/service/PostService.java

[NEST-BE-Fix] Fix boolean logic error

---

src/main/java/com/nest/core/post_management_service/controller/ContentInteractionController.java
src/main/java/com/nest/core/post_management_service/dto/GetArticleResponse.java
src/main/java/com/nest/core/post_management_service/dto/GetPostResponse.java
src/main/java/com/nest/core/post_management_service/service/ContentInteractionService.java

- Add overload to getContent that uses userId and returns posts/articles that uses userId in DTO constructor

[NEST-BE-Fix] Added bookmark count in DTO and fix issue where getting content did not use userId

---

src/main/java/com/nest/core/exception/GlobalExceptionHandler.java

Nest fe fix error

---

src/main/java/com/nest/core/comment_management_service/dto/GetCommentResponse.java
src/main/java/com/nest/core/comment_management_service/model/Comment.java
src/main/java/com/nest/core/comment_management_service/service/CommentService.java
src/main/java/com/nest/core/post_management_service/dto/GetArticleResponse.java
src/main/java/com/nest/core/post_management_service/dto/GetPostResponse.java

[NEST-BE-Fix] Add comment field

[NEST-BE-Fix] Add comment field

---

src/main/java/com/nest/core/comment_management_service/service/CommentService.java

[NEST-BE-Fix] Fix bug where user cannot delete own comment

---

src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/post_management_service/service/PostService.java

[NEST-FIX] fix pagination

---

src/main/java/com/nest/core/post_management_service/controller/ArticleApiController.java
src/main/java/com/nest/core/post_management_service/controller/PostApiController.java
src/main/java/com/nest/core/post_management_service/dto/GetContentStatsResponse.java
src/main/java/com/nest/core/post_management_service/repository/PostRepository.java
src/main/java/com/nest/core/post_management_service/service/ArticleService.java
src/main/java/com/nest/core/post_management_service/service/PostService.java
src/main/java/com/nest/core/report_management_service/service/ReportService.java

**Endpoints**
- /api/v1/article/stats 
- /api/v1/posts/stats
**Notes**
- Only admin and super_admin are allowed to use these endpoints
- Stats include title, topic name, like/view/bookmark/share/comment counts, created time

[NEST-BE-Fix] Create special endpoint for stats

---

src/main/java/com/nest/core/auth_service/config/SecurityConfig.java
src/main/java/com/nest/core/comment_management_service/service/CommentInteractionService.java
src/main/java/com/nest/core/notification_service/controller/NotificationApiController.java
src/main/java/com/nest/core/notification_service/dto/AnnouncementRequest.java
src/main/java/com/nest/core/notification_service/dto/NotificationResponse.java
src/main/java/com/nest/core/notification_service/model/Notification.java
src/main/java/com/nest/core/notification_service/repository/NotificationRepository.java
src/main/java/com/nest/core/notification_service/service/NotificationService.java

[NEST-BE-Notification] Notification

[NEST-BE-Notification] Notification

---

src/main/java/com/nest/core/report_management_service/dto/GetCommentReportResponse.java
src/main/java/com/nest/core/report_management_service/dto/ReportCommentRequest.java
src/main/java/com/nest/core/report_management_service/model/Report.java
src/main/java/com/nest/core/report_management_service/service/ReportService.java

- Refactored Report model to use Comment object instead of only commentId such that contentId can be passed to frontend

[NEST-BE-Fix] Add contentId to comment report DTO

---

src/main/java/com/nest/core/moderation_service/utils/SightEngineUtils.java
src/main/java/com/nest/core/post_management_service/controller/PostApiController.java

- Fixed bug where moderation did not work if image was not included in edit/create post request
- Lowered the threshold of profanity intensity to medium

[NEST-BE-AI-Moderation] Lower Profanity Threshold and Fix Moderation Without Image

---

src/main/java/com/nest/core/moderation_service/utils/SightEngineUtils.java

- Removed self-harm from rules to moderate

[NEST-BE-AI-Moderation] Remove self-harm from moderation rules
